# Generated by Django 4.2.3 on 2023-10-09 02:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('continent', models.CharField(blank=True, max_length=255, null=True)),
                ('access', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='browse.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('speaker', 'speaker'), ('participant', 'participant'), ('depositor', 'depositor'), ('contact', 'contact')], default='participant', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('collection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='browse.collection')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='browse.genre')),
                ('languages', models.ManyToManyField(blank=True, related_name='ses_language', to='browse.language')),
                ('participants', models.ManyToManyField(blank=True, related_name='ses_participant', to='browse.person')),
                ('speakers', models.ManyToManyField(blank=True, related_name='ses_speaker', to='browse.person')),
                ('subgenre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgenres', to='browse.genre')),
                ('working_languages', models.ManyToManyField(blank=True, related_name='ses_wl', to='browse.language')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=5, null=True)),
                ('content', models.FileField(blank=True, upload_to='uploads/')),
                ('session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='browse.session')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coll_contact', to='browse.person'),
        ),
        migrations.AddField(
            model_name='collection',
            name='depositor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coll_depositor', to='browse.person'),
        ),
        migrations.AddField(
            model_name='collection',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coll_lang', to='browse.language'),
        ),
        migrations.AddField(
            model_name='collection',
            name='working_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coll_wl', to='browse.language'),
        ),
    ]
