# Generated by Django 4.2.3 on 2023-08-19 12:57

import browse.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textEAF', models.FilePathField(path=browse.models.currentDir)),
                ('textID', models.IntegerField(unique=True)),
                ('synopsis', models.TextField()),
                ('date', models.DateField()),
                ('languages', models.ManyToManyField(related_name='languages', to='browse.language')),
                ('participants', models.ManyToManyField(related_name='participant', to='browse.person')),
                ('speakers', models.ManyToManyField(related_name='speaker', to='browse.person')),
                ('working_languages', models.ManyToManyField(related_name='working_languages', to='browse.language')),
            ],
        ),
    ]
