# Generated by Django 5.0.7 on 2024-08-16 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotationID', models.CharField(blank=True, max_length=255)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('startTime', models.CharField(blank=True, max_length=50)),
                ('endTime', models.CharField(blank=True, max_length=50)),
                ('transcriptELANfile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_pp', to='browse.file')),
            ],
        ),
    ]
