# Generated by Django 4.2.3 on 2023-08-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatext',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='languages',
            field=models.ManyToManyField(null=True, related_name='languages', to='browse.language'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='synopsis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='working_languages',
            field=models.ManyToManyField(null=True, related_name='working_languages', to='browse.language'),
        ),
    ]
