# Generated by Django 5.0.7 on 2024-08-16 14:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_postprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptELAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotationID', models.CharField(blank=True, max_length=255)),
                ('annotation', models.TextField(blank=True, db_index=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('textType', models.CharField(blank=True, max_length=255)),
                ('startTime', models.CharField(blank=True, max_length=50)),
                ('endTime', models.CharField(blank=True, max_length=50)),
                ('postprocess', models.ManyToManyField(blank=True, to='browse.postprocess')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spk', to='browse.person')),
                ('transcriptELANfile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='browse.file')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vid', to='browse.file')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='browse_tran_search__e1a020_gin')],
            },
        ),
    ]
