# Generated by Django 4.2.3 on 2023-08-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_alter_metatext_date_alter_metatext_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatext',
            name='languages',
            field=models.ManyToManyField(related_name='languages', to='browse.language'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='working_languages',
            field=models.ManyToManyField(related_name='working_languages', to='browse.language'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='browse.genre')),
            ],
        ),
        migrations.AddField(
            model_name='metatext',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='browse.genre'),
        ),
        migrations.AddField(
            model_name='metatext',
            name='subgenre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgenres', to='browse.genre'),
        ),
    ]
