# Generated by Django 4.2.3 on 2023-08-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_alter_metatext_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatext',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='browse.genre'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='languages',
            field=models.ManyToManyField(related_name='language', to='browse.language'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='working_languages',
            field=models.ManyToManyField(related_name='working_language', to='browse.language'),
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='browse.classify')),
            ],
        ),
        migrations.AddField(
            model_name='metatext',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='browse.classify'),
        ),
        migrations.AddField(
            model_name='metatext',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='browse.classify'),
        ),
    ]
