# Generated by Django 5.0.7 on 2024-08-16 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_transcriptelan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceTierType', models.CharField(blank=True, choices=[], max_length=255, null=True)),
                ('destTierType', models.CharField(blank=True, choices=[('text', 'text'), ('gloss', 'gloss'), ('translation', 'translation')], max_length=255, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='browse.collection')),
                ('transcriptELANfile', models.ForeignKey(blank=True, limit_choices_to={'type': 'eaf'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_ref', to='browse.file')),
            ],
        ),
    ]
