# Generated by Django 4.2.3 on 2023-08-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_alter_metatext_genre_alter_metatext_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatext',
            name='textID',
        ),
    ]
