# Generated by Django 5.0.7 on 2024-08-16 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_tierreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='data_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
