# Generated by Django 5.0.7 on 2024-08-16 16:09

import browse.models
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_datasource_data_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='depositor',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='depositor',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=models.SET(functools.partial(browse.models.CONDITIONAL_CASCADE, *(), **{'condition': {'permissions': 'a'}, 'default_value': None})), related_name='coll_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='depositor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coll_depositor', to='browse.person'),
        ),
    ]
