# Generated by Django 4.2.3 on 2023-08-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_remove_metatext_textid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatext',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='browse.classify'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='browse.genre'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='language', to='browse.language'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participant', to='browse.person'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='browse.classify'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='speaker', to='browse.person'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='subgenre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgenres', to='browse.genre'),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='textEAF',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='working_languages',
            field=models.ManyToManyField(blank=True, related_name='working_language', to='browse.language'),
        ),
    ]
