# Generated by Django 4.2.3 on 2023-08-20 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0006_alter_metatext_collection_alter_metatext_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
