# Generated by Django 5.0.7 on 2024-08-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0006_rename_depositor_file_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='access_rights',
            field=models.CharField(choices=[('p', 'public'), ('l', 'login'), ('r', 'restricted'), ('a', 'author only')], default='login', max_length=15),
        ),
        migrations.AlterField(
            model_name='collection',
            name='permissions',
            field=models.CharField(choices=[('p', 'public'), ('l', 'login'), ('r', 'restricted'), ('a', 'author only')], default='login', max_length=15),
        ),
        migrations.AlterField(
            model_name='file',
            name='permissions',
            field=models.CharField(choices=[('p', 'public'), ('l', 'login'), ('r', 'restricted'), ('a', 'author only')], default='login', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='permissions',
            field=models.CharField(choices=[('p', 'public'), ('l', 'login'), ('r', 'restricted'), ('a', 'author only')], default='login', max_length=15),
        ),
    ]
