# Generated by Django 4.2.3 on 2023-08-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_alter_classify_name_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatext',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='textEAF',
            field=models.CharField(max_length=255),
        ),
    ]
