# Generated by Django 5.0.7 on 2024-08-26 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_datasource_access_rights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='browse.collection'),
        ),
        migrations.AlterField(
            model_name='tierreference',
            name='sourceTierType',
            field=models.CharField(blank=True, choices=[('wordbanks-item-number', 'wordbanks-item-number'), ('wordbanks-original-translation', 'wordbanks-original-translation'), ('wordbanks-season', 'wordbanks-season'), ('question', 'question'), ('wordbanks-formal-tsuutina', 'wordbanks-formal-tsuutina'), ('wordbanks-revised-text', 'wordbanks-revised-text'), ('wordbanks-category', 'wordbanks-category'), ('translation', 'translation'), ('wordbanks-original-question', 'wordbanks-original-question'), ('chunk', 'chunk'), ('wordbanks-literal-translation', 'wordbanks-literal-translation'), ('wordbanks-language-unit', 'wordbanks-language-unit'), ('text', 'text'), ('note', 'note'), ('wordbanks-original-text', 'wordbanks-original-text'), ('wordbanks-original-note', 'wordbanks-original-note')], max_length=255, null=True),
        ),
    ]
