# Generated by Django 4.2.3 on 2023-08-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0008_metatext_title_alter_metatext_texteaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatext',
            name='textEAF',
            field=models.TextField(),
        ),
    ]
