# Generated by Django 4.2.3 on 2023-09-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0009_alter_metatext_texteaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('speaker', 'speaker'), ('participant', 'participant')], default='participant', max_length=15),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
