# Generated by Django 4.2.3 on 2023-09-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0010_person_role_alter_metatext_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatext',
            name='fileType',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
