# Generated by Django 4.2.3 on 2023-10-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0011_metatext_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatext',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
