# Generated by Django 4.2.3 on 2023-10-07 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0012_metatext_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='classify',
            name='access',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classify',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='browse.person'),
        ),
        migrations.AddField(
            model_name='classify',
            name='continent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classify',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classify',
            name='depositor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositor', to='browse.person'),
        ),
        migrations.AddField(
            model_name='classify',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coll_lang', to='browse.language'),
        ),
        migrations.AddField(
            model_name='classify',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classify',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classify',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classify',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classify',
            name='working_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coll_wl', to='browse.language'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('speaker', 'speaker'), ('participant', 'participant'), ('depositor', 'depositor'), ('contact', 'contact')], default='participant', max_length=15),
        ),
    ]
