# Generated by Django 4.2.3 on 2023-10-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0013_classify_access_classify_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classify',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classify',
            name='access',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classify',
            name='continent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classify',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classify',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classify',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classify',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
